In [210]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

In [211]:

df = pd.read_csv('Used_Bikes.csv')
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [212]:
df.duplicated().sum()

25324

In [213]:
df.drop_duplicates(inplace=True)

In [214]:
df.duplicated().sum()

0

In [215]:
##  missing value checking  
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [216]:

df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [217]:

dt = {"First Owner":1,"Second Owner":2,"Third Owner":3,"Fourth Owner Or More":4} 
dt

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More': 4}

In [218]:

# for ownership in df['owner']:
#     print(dt[ownership])

df['owner'] = df['owner'].map(dt)

In [219]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [220]:
df['brand'].nunique()

23

In [221]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [222]:
brand_ls = list(df['brand'].value_counts().head(16).keys())
brand_ls

['Bajaj',
 'Royal Enfield',
 'Hero',
 'Honda',
 'Yamaha',
 'TVS',
 'KTM',
 'Suzuki',
 'Harley-Davidson',
 'Kawasaki',
 'Hyosung',
 'Mahindra',
 'Benelli',
 'Triumph',
 'Ducati',
 'BMW']

In [223]:
df2 = df[df['brand'].isin(brand_ls)]
df2.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha

In [224]:

data_dic = {}
i = 1
for brand in list(df2['brand'].value_counts().keys()): 
    data_dic[brand] = i 
    i = i + 1
data_dic

{'Bajaj': 1,
 'Royal Enfield': 2,
 'Hero': 3,
 'Honda': 4,
 'Yamaha': 5,
 'TVS': 6,
 'KTM': 7,
 'Suzuki': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Mahindra': 12,
 'Benelli': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16}

In [225]:

brand_dict  = {brand:i for i , brand in enumerate(list(df2['brand'].value_counts().keys()),start=1)}
print(brand_dict)
df2['brand'] = df2['brand'].map(brand_dict)  
# single time

{'Bajaj': 1, 'Royal Enfield': 2, 'Hero': 3, 'Honda': 4, 'Yamaha': 5, 'TVS': 6, 'KTM': 7, 'Suzuki': 8, 'Harley-Davidson': 9, 'Kawasaki': 10, 'Hyosung': 11, 'Mahindra': 12, 'Benelli': 13, 'Triumph': 14, 'Ducati': 15, 'BMW': 16}

C:\Users\sutha\AppData\Local\Temp\ipykernel_15272\593243193.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['brand'] = df2['brand'].map(brand_dict)

In [226]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha

In [227]:
data_dic = {}
for i,item in enumerate(brand_ls,start=1): 
    data_dic[item]  = i  

data_dic

{'Bajaj': 1,
 'Royal Enfield': 2,
 'Hero': 3,
 'Honda': 4,
 'Yamaha': 5,
 'TVS': 6,
 'KTM': 7,
 'Suzuki': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Mahindra': 12,
 'Benelli': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16}

In [228]:
df2.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,6
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,14
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,6
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,5

In [229]:
df2.drop(['bike_name','city'],axis=1,inplace=True)

C:\Users\sutha\AppData\Local\Temp\ipykernel_15272\1642961446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(['bike_name','city'],axis=1,inplace=True)

In [230]:
df2.head(2)

      price  kms_driven  owner  age  power  brand
0   35000.0     17654.0      1  3.0  110.0      6
1  119900.0     11000.0      1  4.0  350.0      2

In [231]:
x = df2.drop('price',axis=1)
y = df2[['price']]

In [232]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7307 rows x 1 columns]

In [233]:
from sklearn.model_selection import train_test_split 
# scikit-learn

In [234]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)  # 80% training size

In [235]:
from sklearn.linear_model import LinearRegression   # algorithm import

In [236]:
lnr = LinearRegression()

In [237]:
lnr.fit(x_train,y_train)

LinearRegression()

In [238]:
x_train.shape

(5845, 5)

In [239]:
x_train.isnull().sum()

kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [240]:
x_train   # valueerror

      kms_driven  owner  age  power  brand
5199     21000.0      1  5.0  150.0      1
272      13500.0      1  5.0  150.0      1
7472     13007.0      2  6.0  150.0      5
8626     32800.0      1  7.0  150.0      5
1081     28554.0      1  4.0  125.0      1
...          ...    ...  ...    ...    ...
340      14009.0      1  2.0  125.0      1
226      23000.0      2  5.0  220.0      1
6487     20785.0      1  5.0  150.0      1
2569     25000.0      1  8.0  125.0      1
7963     36000.0      1  7.0  125.0      3

[5845 rows x 5 columns]

In [241]:
lnr.score(x_train,y_train)*100    # 75% scored

73.69035406942328

In [242]:

# unseen data or test data or validation data (x_test,y_test)
lnr.score(x_test,y_test)* 100

74.57561596892357

In [243]:
## prediction 
prediction = lnr.predict(x_test)

In [244]:
y_test['prediction'] = prediction

In [245]:
y_test.head(40)

         price     prediction
4789   30000.0   16299.114007
5756   16100.0    2681.718401
8312   23000.0   53012.115373
220    29500.0   -2836.716686
5916   38000.0   35113.301493
4738   20000.0   12169.500065
2179   31000.0   20889.472543
477    70000.0   63617.531105
8167   35000.0   11621.698295
7774  140000.0  135204.466828
5631   58400.0  110460.631514
1574   25500.0  -25109.136318
4513   20500.0   26313.835216
1819   39000.0    2912.268827
6312   50000.0   58833.121071
8162   32000.0   -7324.928500
585    22000.0   36592.854582
5169   70000.0  100504.187633
7268  195200.0  168832.221532
117    35900.0   42122.847854
6690   85000.0   43496.399711
3989   31000.0   15009.693128
5164   22000.0    1230.273003
1753   25100.0   10475.779607
3908   38000.0   11090.634817
4097   50000.0   51382.634049
7476  250000.0  151850.507953
3177   35000.0   33579.751351
4650  120000.0  136608.427747
2465  140000.0  219844.571829
8683   20000.0    6428.781048
4073   30000.0   26432.002066
3322  105000.0  129041.007634
6360   26000.0   28108.611268
2025   70000.0   54945.914333
8003   12000.0  -28379.060801
4045   39000.0   23964.487544
8215  269000.0  181770.740923
844    20400.0   -4154.960858
4838   65000.0   60379.772007

In [246]:
import os  , joblib

In [247]:
os.makedirs('models',exist_ok=True)    # models

In [248]:
lnr     # algorithm and model

LinearRegression()

In [249]:
joblib.dump(lnr,"./models/linear_model.lb")

['./models/linear_model.lb']